apiVersion: v1
kind: ConfigMap

metadata:
  name: grafana-datasource-config
  namespace: smart-water

data:
  prometheus.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        uid: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        editable: true
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: grafana
  namespace: smart-water

spec:
  replicas: 1

  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:
      - name: grafana

        image: grafana/grafana:11.3.1

        ports:
        - containerPort: 3000

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi

        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 20

        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin

        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin

        volumeMounts:
        - name: grafana-datasource-config
          mountPath: /etc/grafana/provisioning/datasources/prometheus.yml
          subPath: prometheus.yml

      volumes:
      - name: grafana-datasource-config
        configMap:
          name: grafana-datasource-config
