apiVersion: v1
kind: Secret

metadata:
  name: smart-water-secret
  namespace: smart-water

type: Opaque

stringData:
  DB_USER: admin
  DB_PASSWORD: change-this-password
  SMTP_USER: alerts@example.com
  SMTP_PASSWORD: change-this-smtp-password
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/example
