apiVersion: v1
kind: Secret

metadata:
  name: smart-water-secret
  namespace: smart-water

type: Opaque

stringData:
  DB_USER: admin
  DB_PASSWORD: admin123
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  SLACK_WEBHOOK_URL: ""
