import { useEffect, useState } from "react";
import { fetchAlerts } from "../api/client.js";
import PageHeader from "../components/PageHeader.jsx";
import StatusBadge from "../components/StatusBadge.jsx";

function Alerts() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const loadAlerts = async () => {
      try {
        setLoading(true);
        setAlerts(await fetchAlerts());
        setError("");
      } catch (err) {
        setError(err.message || "Unable to load alerts");
      } finally {
        setLoading(false);
      }
    };

    loadAlerts();
  }, []);

  return (
    <section>
      <PageHeader
        eyebrow="Alert Center"
        title="Low Water Alert History"
        description="Review every alert generated by the notification service when tank levels fall below threshold."
      />

      {error && <div className="alert-message">{error}</div>}

      <article className="panel table-panel">
        <div className="panel-header">
          <div>
            <p className="eyebrow">History</p>
            <h2>Recorded Alerts</h2>
          </div>
          <StatusBadge level="neutral">
            {loading ? "Loading" : `${alerts.length} Events`}
          </StatusBadge>
        </div>

        <div className="responsive-table">
          <table>
            <thead>
              <tr>
                <th>ID</th>
                <th>Tank</th>
                <th>Level</th>
                <th>Type</th>
                <th>Created</th>
              </tr>
            </thead>
            <tbody>
              {alerts.map((alert) => (
                <tr key={alert.id}>
                  <td>#{alert.id}</td>
                  <td>{alert.tank_name}</td>
                  <td>
                    <StatusBadge level="critical">
                      {alert.water_level}%
                    </StatusBadge>
                  </td>
                  <td>{alert.alert_type}</td>
                  <td>{new Date(alert.created_at).toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {!loading && alerts.length === 0 && (
          <p className="empty-state">No alert history is available.</p>
        )}
      </article>
    </section>
  );
}

export default Alerts;
